source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'mysql2'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'will_paginate', '~> 2.0'
gem 'settingslogic'                                                             
gem 'fastercsv'                                                                 
gem 'rest-client'                                                               
gem 'mechanize'                                                                 
gem 'json', '1.5.0'
gem 'rake',  '0.8.7'
gem 'activerecord-mysql2-adapter','0.0.3'
gem 'bundler'
