source 'http://rubygems.org'

gem 'rails', '2.3.5'
gem 'rake',  '0.8.3'
gem 'fastercsv'
gem 'rcov'
gem 'rdoc',  '3.8'
gem 'warden', '0.10.7'
gem 'devise', '1.0.11'
gem 'json'
gem 'settingslogic'
gem 'rest-client', '1.6.1'
gem 'mechanize'
